---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build-docker
    image: plugins/docker
    repo: amritanshu16/nexus3:latest
    when:
      branch: master
