---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build-docker
    image: plugins/docker
    settings:
      repo: amritanshu16/nexus3
      tag:
        - arm64
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: master